### ISSUE TITLE
Type definition errors in 3.10.0

### ISSUE THREAD

**Issue by jeffwhelpley** [versatica/JsSIP#838]
When I upgrade from 3.9.1 to 3.10.0 and run the TypeScript compiler over my code, I get type definition errors from within the jssip library itself:

```
node_modules/jssip/lib/RTCSession.d.ts:1:23 - error TS2305: Module '"events"' has no exported member 'Listener'.

1 import {EventEmitter, Listener} from 'events'
                        ~~~~~~~~

node_modules/jssip/lib/UA.d.ts:1:23 - error TS2305: Module '"events"' has no exported member 'Listener'.

1 import {EventEmitter, Listener} from 'events'
```

**Comment by jmillan** [comment]
`Listener` is no longer imported since latest release.
